CREATE DATABASE IF NOT EXISTS carousel_party_db;

USE carousel_party_db;

CREATE TABLE IF NOT EXISTS songs (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  active TINYINT DEFAULT 1,
  likecount INT DEFAULT 0,
  dislikecount INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
